### PR TITLE
[OSDEV-999] Implement verification for header error in the facility list upload and API upload endpoints.

### PR DESCRIPTION
**Pull request by roman-stolar**
[OSDEV-999](https://opensupplyhub.atlassian.net/browse/OSDEV-999) Implement verification for header error in the facility list upload and API upload endpoints.

- Handled header validation for API & List Upload

### CODE REVIEW

**Comment by roman-stolar** [comment]
PR is ready for review.
I'm testing changes locally.

**Review by vladsha-dev — CHANGES_REQUESTED** [review]
I updated the сс-fix-facility-uploads branch with the latest updates from the main branch. Please rebase this one.

**Review by vladsha-dev — CHANGES_REQUESTED** [review]
1. Please update/edit the RELEASE-NOTES file.
2. You may assign this PR to yourself.

**Comment by roman-stolar** [comment]
Tested locally with API upload & List upload (.csv, .xlxs).

**Review by mazursasha1990 — APPROVED** [review]
LGTM

**Pull request merged**
