### PR TITLE
[OSDEV-1072] Added building database-anonymizer container to the pipeline.

### PR DESCRIPTION
**Pull request by roninzp**
* [OSDEV-1072](https://opensupplyhub.atlassian.net/browse/OSDEV-1072) - The following changes have been made:
    * Added building database-anonymizer container to the pipeline.
    * Pushing the database-anonymizer container to the repo is turned off until the database anonymizing scheduled task will be deployed to the production.

### CODE REVIEW

**Review by vladsha-dev — CHANGES_REQUESTED** [review]
Please update the RELEASE-NOTES.md file to reflect the changes you made.

**Review by vladsha-dev — APPROVED** [review]
LGTM

**Review by VadimKovalenkoSNF — DISMISSED** [review]
Approved

**Review by VadimKovalenkoSNF — APPROVED** [review]
Approved

**Pull request merged**
