### PR TITLE
[OSDEV-1075] Added tags propagation to batch job definition

### PR DESCRIPTION
**Pull request by roninzp**
* [OSDEV-1075](https://opensupplyhub.atlassian.net/browse/OSDEV-1075) - The following changes have been made:
    * All resources created via batch job will be tagged

### CODE REVIEW

**Review by killev — APPROVED** [review]

**Review by roman-stolar — APPROVED** [review]
LGTM

**Review by vladsha-dev — CHANGES_REQUESTED** [review]
Please update the RELEASE-NOTES.md file to reflect the changes you made.

**Review by vladsha-dev — APPROVED** [review]
LGTM

**Review by VadimKovalenkoSNF — DISMISSED** [review]
Approved

**Review by killev — APPROVED** [review]
LGTM, Approved

**Review by killev — APPROVED** [review]

**Review by roman-stolar — APPROVED** [review]

**Pull request merged**
