### PR TITLE
Add 'Staging' and 'Production' to selection

### PR DESCRIPTION
**Pull request by killev**
Add possibility to select 'Staging' and 'Production' when manually start deploy

### CODE REVIEW

**Review by vladsha-dev — CHANGES_REQUESTED** [review]
Looks like such statements should also be updated.
Screenshot 2024-02-22 at 15 59 47

**Comment by roman-stolar** [comment]
> Looks like such statements should also be updated. Screenshot 2024-02-22 at 15 59 47

@vladsha-dev In case that we choose environment from selection (manually) the variable will be taken from **inputs.deploy-env** instead of branches that state could pass through **Development** & **Pre-Prod**. So it should work properly. In future if we want to trigger deployment of staging & production by tags it should be updated.

**Comment by vladsha-dev** [comment]
> > Looks like such statements should also be updated. Screenshot 2024-02-22 at 15 59 47
> 
> @vladsha-dev In case that we choose environment from selection (manually) the variable will be taken from **inputs.deploy-env** instead of branches that state could pass through **Development** & **Pre-Prod**. So it should work properly. In future if we want to trigger deployment of staging & production by tags it should be updated.

Didn't grasp the logic the first time, thanks!

**Review by vladsha-dev — APPROVED** [review]
LGTM

**Pull request merged**
