### PR TITLE
[OSDEV-1169] allow deploying database anonymizer to production

### PR DESCRIPTION
**Pull request by roninzp**
This will allow us to create a copy of the database with anonymized data every Saturday.

### CODE REVIEW

**Review by roman-stolar — DISMISSED** [review]

**Review by vladsha-dev — APPROVED** [review]
LGTM

**Review by vladsha-dev — CHANGES_REQUESTED** [review]
Hi @roninzp,
Please update the RELEASE-NOTES.md file accordingly. I think it should be added to the Architecture/Environment changes section of the 1.19.0 version.

**Comment by roninzp** [comment]
@vladsha-dev 
Done

**Review by vladsha-dev — APPROVED** [review]
LGTM

**Review by VadimKovalenkoSNF — APPROVED** [review]
Approved

**Pull request merged**
