### PR TITLE
[OSDEV-953] Increase configuration for test environment

### PR DESCRIPTION
**Pull request by killev**
[OSDEV-953](https://opensupplyhub.atlassian.net/browse/OSDEV-953) Increase configuration for test environment
- Updated Dedupe Hub config .tfvars file for **Test**:
     * 4 CPU
     * 8 GB Memory
- Added job to update Dedupe Hub service with new Image

### CODE REVIEW

**Comment by roman-stolar** [comment]
@killev We can closed this PR as it duplicate of https://github.com/opensupplyhub/open-supply-hub/pull/105

**Review by roman-stolar — DISMISSED** [review]

**Review by VadimKovalenkoSNF — DISMISSED** [review]
Lgtm

**Review by roman-stolar — APPROVED** [review]

**Review by VadimKovalenkoSNF — DISMISSED** [review]
Approved

**Comment by vladsha-dev** [comment]
@roman-stolar please update the description of the PR. It is not up-to-date

**Review by roman-stolar — APPROVED** [review]

**Review by vladsha-dev — APPROVED** [review]
LGTM

**Pull request merged**
