### PR TITLE
[OSDEV-1448] Make tile query work with multiple arguments

### PR DESCRIPTION
**Pull request by killev**
Use tuple concatenation instead of converting to array.

### CODE REVIEW

**Comment by killev** [comment]
@coderabbitai summary

**Comment by killev** [comment]
https://github.com/coderabbitai summary

**Comment by killev** [comment]
@coderabbitai summary

**Review by VadimKovalenkoSNF — CHANGES_REQUESTED** [review]
Pls, update Release notes for this bug.

**Comment by roman-stolar** [comment]
+1 about release notes

**Review by VadimKovalenkoSNF — APPROVED** [review]
Approved.

**Review by vladsha-dev — APPROVED** [review]
LGTM

**Review by roman-stolar — APPROVED** [review]

**Pull request merged**
