### PR TITLE
[OSDEV-944] Facility claims. Short-term new screen for claim documentation.

### PR DESCRIPTION
**Pull request by VadimKovalenkoSNF**
Fix https://opensupplyhub.atlassian.net/browse/OSDEV-944

1. Prepare basic FE for the file upload - DONE.
2. Connect to Redux state - DONE.
7. Change: **LinkedIn Profile** in current claims flow to **Link to Facility LinkedIn Profile** - DONE
8. Create model for storing uploaded attachments in PostgreSQL - DONE.
9. Add FE and BE validation (file size, file extensions, amount of files) - DONE.
10. Connect BE - DONE.
11. Connect S3 bucket - DONE.
12. Depict file links in [Facility Claims dashboard](https://opensupplyhub.org/dashboard/claims) per claim - DONE.
13. Add unit tests - DONE.
14. Remove related TODOs in this PR - DONE.
15. Update RELEASE_NOTES - DONE.

**Improvements related to text fields during claim flow**

1. Remove field for **Preferred method of contact** (preferred contact method can be deleted from database)  - TO BE DONE IN SEPARATE TICKET.
3. Adding the LinkedIn for the person’s contact - TO BE DONE IN SEPARATE TICKET.
4. Remove **Any additional details?** text field - TO BE DONE IN SEPARATE TICKET.

### CODE REVIEW

**Comment by roman-stolar** [comment]
@VadimKovalenkoSNF S3 bucket will be connected in scope of this PR/task or as seperate PR/task?

**Comment by VadimKovalenkoSNF** [comment]
@VadimKovalenkoSNF S3 bucket is already connected for this task - it works the same way as for the facility lists. Each Django model that expect [FileField](https://github.com/opensupplyhub/open-supply-hub/pull/155/files#diff-c11ad0b5417ed24283e7af5a03a55971a7639799bbd247e13cdb35253c7348e8R33) will store data to S3 implicitly. If you need info about local connection to the S3, contact me or @vladsha-dev

**Review by vladsha-dev — APPROVED** [review]
LGTM
Greate job!

**Review by roman-stolar — APPROVED** [review]
LGTM! Approved.

**Pull request merged**
