### PR TITLE
[OSDEV-1102] Propagate production location updates to OpenSearch (match promote, split)

### PR DESCRIPTION
**Pull request by Innavin369**
[OSDEV-1102](https://opensupplyhub.atlassian.net/browse/OSDEV-1102) Propagate production location updates to OpenSearch (match promote, split)

This PR adds functionality to refresh the updated_at field during the promotion and splitting of facilities. This change is necessary because the extended fields for both the new and old facilities are updated via triggers within these methods, and refreshing updated_at ensures accurate tracking of the most recent modifications.

[OSDEV-1102]: https://opensupplyhub.atlassian.net/browse/OSDEV-1102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by VadimKovalenkoSNF — APPROVED** [review]
Approved.

**Comment by mazursasha1990** [comment]
Please fix conflicts.
Remove unnecessary `)` in the link to the ticket in the PR description.

What do you think about changing the description to this:

> This PR adds functionality to refresh the `updated_at` field during the promotion and splitting of facilities. This change is necessary because the extended fields for both the new and old facilities are updated via triggers within these methods, and refreshing `updated_at` ensures accurate tracking of the most recent modifications.

**Review by VadimKovalenkoSNF — APPROVED** [review]
Lgtm

**Review by vladsha-dev — APPROVED** [review]
LGTM

**Pull request merged**
