### PR TITLE
[OSDEV-1127] Update the helper text for the OS ID input

### PR DESCRIPTION
**Pull request by mazursasha1990**
[OSDEV-1127](https://opensupplyhub.atlassian.net/browse/OSDEV-1127) - SLC. Implement OS ID search.

In this PR, the helper text for the OS ID input was updated to match the layouts.

[OSDEV-1127]: https://opensupplyhub.atlassian.net/browse/OSDEV-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by vladsha-dev — COMMENTED** [review]
LGTM but could you please fix the test?

**Review by vladsha-dev — APPROVED** [review]
LGTM

**Review by VadimKovalenkoSNF — CHANGES_REQUESTED** [review]
It looks like this change won't go to the upcoming 1.22 release. If so, pls update release notes with respected notes. If not - create a PR with these changes that will be merged into the `releases/v.1.22` branch. This PR will be treated as a back-merge then.

**Review by VadimKovalenkoSNF — APPROVED** [review]
Approved

**Pull request merged**
