### PR TITLE
[OSDEV-1177] Activate stopping Logstash and correct grammar mistakes in "DB - Apply Anonymized DB" and "Deploy to AWS" GitHub workflows.

### PR DESCRIPTION
**Pull request by vladsha-dev**
[[OSDEV-1177](https://opensupplyhub.atlassian.net/browse/OSDEV-1177)]
- Removed the "if" clause in the DB - Apply Anonymized DB workflow to activate the stopping of Logstash.
- Corrected grammar mistakes in the description of the job steps for stopping Logstash and clearing OpenSearch for the "DB - Apply Anonymized DB" and "Deploy to AWS" GitHub workflows.

[OSDEV-1177]: https://opensupplyhub.atlassian.net/browse/OSDEV-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by roman-stolar — APPROVED** [review]
LGTM, just want to be sure it should be in **Bugfix** topic instead of **Architecture/Environment changes** @vladsha-dev

**Review by VadimKovalenkoSNF — APPROVED** [review]
Approved

**Comment by vladsha-dev** [comment]
> LGTM, just want to be sure it should be in **Bugfix** topic instead of **Architecture/Environment changes** @vladsha-dev

I believe it is better to keep it in Bugfix because DB - Apply Anonymized DB doesn't work properly :(

**Review by roninzp — APPROVED** [review]
LGTM

**Review by killev — APPROVED** [review]
LGTM

**Pull request merged**
