### PR TITLE
PR Analytics workflow

### PR DESCRIPTION
**Pull request by roman-stolar**
PR Analytics workflow for Pull Request (Weekly report)
[Github Action](https://github.com/marketplace/actions/pull-request-analytics)

### CODE REVIEW

**Comment by roman-stolar** [comment]
How report will looks like -> https://github.com/opensupplyhub/open-supply-hub/issues/169

**Comment by vladsha-dev** [comment]
@roman-stolar Is it still relevant?
If yes, could you please share more details on the purpose of it?

**Review by vladsha-dev — CHANGES_REQUESTED** [review]
@roman-stolar Is it still relevant?
If yes, could you please share more details on the purpose of it?

**Comment by roman-stolar** [comment]
Outdated

**Pull request closed without merging**
