### PR TITLE
[OSDEV-1177] Added OpenSearch index cleaning to "DB - Apply Anonymized DB" pipeline

### PR DESCRIPTION
**Pull request by roninzp**
Implemented clearing OpenSearch and stopping Logstash during anonymized Postgres DB restore in pre-prod/test environments to freshly populate OpenSearch with data from the restored Postgres DB.

### CODE REVIEW

**Review by vladsha-dev — CHANGES_REQUESTED** [review]
@roninzp please update the RELEASE-NOTES file

**Comment by roninzp** [comment]
> @roninzp please update the RELEASE-NOTES file

This task has already been added to the RELEASE-NOTES file.
https://github.com/opensupplyhub/open-supply-hub/blob/main/doc/release/RELEASE-NOTES.md#architectureenvironment-changes

**Review by vladsha-dev — APPROVED** [review]
LGTM

**Review by VadimKovalenkoSNF — APPROVED** [review]
LGTM

**Pull request merged**
