### PR TITLE
[OSDEV-272] Adjust sorting for accented strings

### PR DESCRIPTION
**Pull request by VadimKovalenkoSNF**
Introduce right sorting for accented strings as follow-up patch for [OSDEV-272](https://opensupplyhub.atlassian.net/browse/OSDEV-272)

[OSDEV-272]: https://opensupplyhub.atlassian.net/browse/OSDEV-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by roman-stolar — COMMENTED** [review]
@VadimKovalenkoSNF I think we also need to update release-notes and include information about accented strings there.

**Comment by VadimKovalenkoSNF** [comment]
@roman-stolar , good point. I've updated this info in Release Notes.

**Review by roman-stolar — APPROVED** [review]
LGTM

**Review by Innavin369 — APPROVED** [review]
LGTM

**Review by mazursasha1990 — DISMISSED** [review]
LGTM

**Review by roman-stolar — APPROVED** [review]
LGTM

**Review by Innavin369 — APPROVED** [review]

**Pull request merged**
