### PR TITLE
[OSDEV-1184] Add size param validation

### PR DESCRIPTION
**Pull request by VadimKovalenkoSNF**
Follow-up PR [OSDEV-1184](https://opensupplyhub.atlassian.net/browse/OSDEV-1184) that introduces validation of the size parameter.

Size parameter:
1. Should be positive integer
2. Should be less or equal to our current OpenSearch output limit (250 entries) 

[OSDEV-1184]: https://opensupplyhub.atlassian.net/browse/OSDEV-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by vladsha-dev — APPROVED** [review]
LGTM

**Review by mazursasha1990 — CHANGES_REQUESTED** [review]
Please change the Release-notes.

**Comment by VadimKovalenkoSNF** [comment]
> Please change the Release-notes.

@mazursasha1990 no need to change release notes, everything related to **OSDEV-1184** already there.

**Comment by mazursasha1990** [comment]
> > Please change the Release-notes.
> 
> @mazursasha1990 no need to change release notes, everything related to **OSDEV-1184** already there.

I see. 
Thanks.

**Review by mazursasha1990 — APPROVED** [review]
LGTM

**Pull request merged**
