### PR TITLE
[OSDEV-876] Update deployment workflows to make them run in the new repository

### PR DESCRIPTION
**Pull request by mazursasha1990**
[OSDEV-876](https://opensupplyhub.atlassian.net/browse/OSDEV-876) - Deployment. Update deployment workflows to make them run in the new repository.

The following changes were implemented:

- updated expression for environment name for all jobs in the `Deploy to AWS` workflow;
- updated versions of external actions for GitHub Actions workflows: `[Release] Init` and `[Release] Deploy`;
- updated release protocol;

### CODE REVIEW

**Review by VadimKovalenkoSNF — APPROVED** [review]
Approved

**Review by Innavin369 — DISMISSED** [review]

**Comment by roman-stolar** [comment]
@mazursasha1990 So versions update resolve the issue?

**Review by killev — CHANGES_REQUESTED** [review]
The issue is that after creating release tag, new build has failed becase it can't select correct environment.

Environment is selecting by the likes like this:

**Comment by roman-stolar** [comment]
@mazursasha1990 Did you test latest env variable update for staging (init-plan) from your branch?

**Comment by mazursasha1990** [comment]
> @mazursasha1990 Did you test latest env variable update for staging (init-plan) from your branch?

@roman-stolar Not yet.

**Review by roman-stolar — APPROVED** [review]
In general LGTM

**Review by killev — APPROVED** [review]
LGTM, Approved

**Review by Innavin369 — APPROVED** [review]

**Pull request merged**
